export const listingData = [
  {
    id: "6626ffd2addbca5e5c29a195",
    thumbnail: "https://source.unsplash.com/random?driveway&13",
    images: [
      "https://source.unsplash.com/random?parking-spot&13",
      "https://source.unsplash.com/random?parking-spot&14",
      "https://source.unsplash.com/random?parking-spot&15",
    ],
    coordinates: {
      latitude: 44.9727,
      longitude: -93.23540000000003,
    },
    city: "Minnetonka",
    state: "Minnesota",
    listingType: "Parking Spot",
    price: 7.25,
    duration: "hour",
    relist: true,
    relistDuration: "day",
    description: "Secure and conveniently located parking spot perfect for event-goers or concert enthusiasts. Enjoy peace of mind with our 24/7 surveillance and easy access.",
    active: true,
    availability: [
      {
        day: "Monday",
        availableHours: ["14:00-16:00", "18:00-20:00"],
        isAvailable: true,
      },
      {
        day: "Tuesday",
        availableHours: ["11:00-13:00"],
        isAvailable: false,
      },
      {
        day: "Wednesday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Thursday",
        availableHours: ["11:00-16:00"],
        isAvailable: true,
      },
      {
        day: "Friday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Saturday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Sunday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
    ],
    distance: 0,
    rating: 4.65,
    reviews: 26,
    date: "2024-04-01T14:23:00Z",
    ends: "2024-04-09T16:26:00Z",
    bids: 12,
    capacity: 4,
    spotsLeft: 2,
    tags: ["Events", "Concerts"],
    amenities: ["Near Venue", "Covered Parking", "24/7 Access", "Surveillance", "Oversized Vehicles", "Gated", "Lighting", "Electric Charging"],
    seller: {
      id: "6628a522fe82e9bdd501183f",
      name: "John Doe",
      description: "I'm a friendly and reliable host who enjoys meeting new people and providing a safe and secure parking experience.",
      rating: 4.8,
      reviews: 31,
      city: "Minnetonka",
      state: "MN",
      profilePicture: "https://source.unsplash.com/random?person&1",
      activeSince: "2023-02-02T14:23:00Z",
      verified: true,
      listings: [],
    },
    spotReviews: [
      {
        id: "6628a9aefe82e9bdd50a5a97",
        rating: 4.5,
        review: "Great spot! Very convenient and secure.",
        date: "2024-03-01T14:23:00Z",
        reviewer: {
          id: "6628a94afe82e9bdd5099c06",
          name: "Jane Doe",
          city: "Minnetonka",
          state: "MN",
          profilePicture: "https://source.unsplash.com/random?person&3",
        },
      },
    ],
  },
  {
    id: "6626fed9addbca5e5c27bb54",
    thumbnail: "https://source.unsplash.com/random?parking-spot&5",
    images: [
      "https://source.unsplash.com/random?parking-spot&5",
      "https://source.unsplash.com/random?parking-spot&6",
      "https://source.unsplash.com/random?parking-spot&7",
      "https://source.unsplash.com/random?parking-spot&8",
    ],
    coordinates: {
      latitude: 44.3,
      longitude: -93.23540000000003,
    },
    city: "Minnetonka",
    state: "Minnesota",
    listingType: "Driveway",
    price: 13.74,
    duration: "hour",
    relist: true,
    relistDuration: "week",
    description: "Ideal driveway spot for sports fans. Features include 24/7 access, lighting for night time, and an electric charging station. A perfect match for your game day parking needs.",
    active: true,
    availability: [
      {
        day: "Monday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Tuesday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Wednesday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Thursday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Friday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Saturday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
      {
        day: "Sunday",
        availableHours: ["00:00-23:59"],
        isAvailable: true,
      },
    ],
    distance: 0,
    rating: 4.98,
    reviews: 26,
    date: "2024-04-09T14:23:00Z",
    ends: "2024-04-012T16:26:00Z",
    bids: 19,
    capacity: 2,
    spotsLeft: 1,
    tags: ["Sports"],
    amenities: ["24/7 Access", "Lighting", "Electric Charging"],
    seller: {
      id: "6628a4ebfe82e9bdd500aa2b",
      name: "Dris Elamri",
      description: "I'm a sports enthusiast who enjoys hosting fellow fans for game day parking.",
      rating: 4.3,
      reviews: 12,
      city: "Excelsior",
      state: "MN",
      profilePicture: "https://source.unsplash.com/random?person&2",
      activeSince: "2023-04-05T14:23:00Z",
      verified: false,
      listings: [],
    },
    spotReviews: [
      {
        id: "6628a8b9fe82e9bdd5086e29",
        rating: 4.5,
        review: "Great spot! Very convenient and secure.",
        date: "2024-03-01T14:23:00Z",
        reviewer: {
          id: "6628a94afe82e9bdd5099c06",
          name: "Jane Doe",
          city: "Minnetonka",
          state: "MN",
          profilePicture: "https://source.unsplash.com/random?person&3",
        },
      },
    ],
  },
];
